### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by bnarasimhanaidu** [hrestrepop/ngx-weditor#4]
ERROR in node_modules/ngx-weditor/lib/toolbar/toolbar.component.d.ts(2,31): error TS2307: Cannot find module 'ngx-bootstrap/popover'.
 after install and run in angular shows above error

**Comment by hrestrepop** [comment]
Hi @bnarasimhanaidu.
Sorry that I haven't updated the docs, I will soon.

May you try npm install `npm install -S ngx-bootstrap` ? 

Thanks for reporting.
