### ISSUE TITLE
Build --prod not working

### ISSUE THREAD

**Issue by MistaMadeDev** [hrestrepop/ngx-weditor#5]
**Describe the bug**
When I launch my program with ng serve all it's ok, same result with ng build.
But when I try to compile my Angular 6 project with ng build --prod I can't.
If I delete NgxWeditorModule the project build correctly.

**To Reproduce**
I have a lot of import on my project:
![image](https://user-images.githubusercontent.com/42675520/44588247-7c3b9980-a7b5-11e8-9d99-3c0775125b22.png)

It's posible that your module is not compatible with an other?

**Expected behavior**
Could you help me to build my project please.

**Screenshots**
![image](https://user-images.githubusercontent.com/42675520/44588147-41396600-a7b5-11e8-8b92-68b88b50ee5a.png)

**Comment by hrestrepop** [comment]
Hey @MistaMadeDev 

Thanks for reporting. 
I'm fixing it as soon as possible. I will notify you today later.

**Comment by MistaMadeDev** [comment]
Thanks for your fast reply.
See you later ;)

**Comment by hrestrepop** [comment]
@MistaMadeDev Try 1.0.7 version.

**Comment by MistaMadeDev** [comment]
It works!
Thank you so much.
