### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by jfvilasAbanca** [hrestrepop/ngx-weditor#9]
Hi there.

Thanks for your work.

I've installed the component in my ang6 application and the editor seems to work fine, but there are some missing icons on the menu toolbar (see attached file).

![Untitled](https://user-images.githubusercontent.com/22166417/77904854-8a9d4180-7285-11ea-9d8e-1b49386cce24.png)

**Comment by hrestrepop** [comment]
Package has been updated to Angular 9
